spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8083/
          predicates:
            - Path=/client/**

        - id: r2
          uri: http://localhost:8084/
          predicates:
            - Path= /produits/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders : "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE


